//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright 2022 Aaron Weisberg.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1

import (
	"k8s.io/apimachinery/pkg/labels"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DynamicAuthorizationPolicy) DeepCopyInto(out *DynamicAuthorizationPolicy) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DynamicAuthorizationPolicy.
func (in *DynamicAuthorizationPolicy) DeepCopy() *DynamicAuthorizationPolicy {
	if in == nil {
		return nil
	}
	out := new(DynamicAuthorizationPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DynamicAuthorizationPolicy) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DynamicAuthorizationPolicyList) DeepCopyInto(out *DynamicAuthorizationPolicyList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]DynamicAuthorizationPolicy, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DynamicAuthorizationPolicyList.
func (in *DynamicAuthorizationPolicyList) DeepCopy() *DynamicAuthorizationPolicyList {
	if in == nil {
		return nil
	}
	out := new(DynamicAuthorizationPolicyList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DynamicAuthorizationPolicyList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DynamicAuthorizationPolicySpec) DeepCopyInto(out *DynamicAuthorizationPolicySpec) {
	*out = *in
	if in.DynamicPolicies != nil {
		in, out := &in.DynamicPolicies, &out.DynamicPolicies
		*out = make([]DynamicPolicy, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DynamicAuthorizationPolicySpec.
func (in *DynamicAuthorizationPolicySpec) DeepCopy() *DynamicAuthorizationPolicySpec {
	if in == nil {
		return nil
	}
	out := new(DynamicAuthorizationPolicySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DynamicAuthorizationPolicyStatus) DeepCopyInto(out *DynamicAuthorizationPolicyStatus) {
	*out = *in
	if in.ServiceAccountPolicyMapping != nil {
		in, out := &in.ServiceAccountPolicyMapping, &out.ServiceAccountPolicyMapping
		*out = make(ServiceAccountPolicyMapping, len(*in))
		for key, val := range *in {
			var outVal map[string]bool
			if val == nil {
				(*out)[key] = nil
			} else {
				in, out := &val, &outVal
				*out = make(HashSet, len(*in))
				for key, val := range *in {
					(*out)[key] = val
				}
			}
			(*out)[key] = outVal
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DynamicAuthorizationPolicyStatus.
func (in *DynamicAuthorizationPolicyStatus) DeepCopy() *DynamicAuthorizationPolicyStatus {
	if in == nil {
		return nil
	}
	out := new(DynamicAuthorizationPolicyStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DynamicPolicy) DeepCopyInto(out *DynamicPolicy) {
	*out = *in
	if in.PodSelectors != nil {
		in, out := &in.PodSelectors, &out.PodSelectors
		*out = make(labels.Set, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DynamicPolicy.
func (in *DynamicPolicy) DeepCopy() *DynamicPolicy {
	if in == nil {
		return nil
	}
	out := new(DynamicPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in HashSet) DeepCopyInto(out *HashSet) {
	{
		in := &in
		*out = make(HashSet, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HashSet.
func (in HashSet) DeepCopy() HashSet {
	if in == nil {
		return nil
	}
	out := new(HashSet)
	in.DeepCopyInto(out)
	return *out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in ServiceAccountPolicyMapping) DeepCopyInto(out *ServiceAccountPolicyMapping) {
	{
		in := &in
		*out = make(ServiceAccountPolicyMapping, len(*in))
		for key, val := range *in {
			var outVal map[string]bool
			if val == nil {
				(*out)[key] = nil
			} else {
				in, out := &val, &outVal
				*out = make(HashSet, len(*in))
				for key, val := range *in {
					(*out)[key] = val
				}
			}
			(*out)[key] = outVal
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServiceAccountPolicyMapping.
func (in ServiceAccountPolicyMapping) DeepCopy() ServiceAccountPolicyMapping {
	if in == nil {
		return nil
	}
	out := new(ServiceAccountPolicyMapping)
	in.DeepCopyInto(out)
	return *out
}
