# permissions for end users to view dynamicauthorizationpolicies.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: dynamicauthorizationpolicy-viewer-role
rules:
- apiGroups:
  - peerauth.aweis.io
  resources:
  - dynamicauthorizationpolicies
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - peerauth.aweis.io
  resources:
  - dynamicauthorizationpolicies/status
  verbs:
  - get
