---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - peerauth.aweis.io
  resources:
  - dynamicauthorizationpolicies
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - peerauth.aweis.io
  resources:
  - dynamicauthorizationpolicies/finalizers
  verbs:
  - update
- apiGroups:
  - peerauth.aweis.io
  resources:
  - dynamicauthorizationpolicies/status
  verbs:
  - get
  - patch
  - update
