apiVersion: peerauth.aweis.io/v1
kind: DynamicAuthorizationPolicy
metadata:
  name: dynamicauthorizationpolicy-sample
spec:
  dynamicPolicies:
    - name: foo
      trustDomain: cluster.local
      podSelectors:
        app: user-access-service
    - name: java
      trustDomain: cluster.local
      podSelectors:
        app.kubernetes.io/name: app-java
